# Generated by Django 4.2.4 on 2023-10-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
